# Generated by Django 3.2.8 on 2021-10-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caption',
            new_name='FrameCaption',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='FrameTag',
        ),
    ]
