# Generated by Django 3.2.8 on 2021-10-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20211024_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtractedImage',
            new_name='ExtractedFrame',
        ),
    ]
