# Generated by Django 3.2.6 on 2021-10-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='count_view',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
