# Generated by Django 3.2.8 on 2021-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_picture_count_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='caption',
            field=models.ManyToManyField(blank=True, to='gallery.Caption'),
        ),
    ]
