# Generated by Django 3.2.8 on 2021-10-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedimage',
            name='tag',
            field=models.ManyToManyField(blank=True, to='pdfs.PDF_Tag'),
        ),
    ]
